# Generated by Django 4.0.2 on 2022-03-29 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]