# Generated by Django 4.0.2 on 2022-04-27 08:39

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), users.validators.ImageSizeValidator(max_size=(4000, 3000), min_size=(1200, 900))]),
        ),
    ]
