# Generated by Django 4.0.2 on 2022-05-01 11:29

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=80)),
                ('domain', models.CharField(max_length=80, help_text='For example: test.com')),
                ('favicon', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'ico']), users.validators.ImageSizeValidator(max_size=(144, 144), min_size=(16, 16))])),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
    ]
